project:
  type: book
  output-dir: docs

book:
  title: "Open Science Handbook"
  author: "Bawan Amin"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - preregistration.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



